- name: Add Remmina PPA
  apt_repository:
    repo: ppa:remmina-ppa-team/remmina-next
    codename: "{{ubuntu_codename}}"

- name: Install Remmina
  apt:
    name:
      - remmina
      - remmina-plugin-rdp
      - libfreerdp-plugins-standard
