---
- name: setup linux mint
  hosts: localhost
  vars_files:
    - vars.yml
  become: true

  pre_tasks:
    - name: upgrade apt repositories
      apt:
        update_cache: true

  roles:
    - system
    - desktop
    - git
    - utils
    - internet
    - collaboration
    - virtualbox
    - vscode
    - insync
    - remmina
    - tmux
    - vim
    - vagrant
    - node

  post_tasks:
    - name: cleanup apt packages
      apt:
        autoclean: true
        autoremove: true

# - hosts: localhost
#   become: true
#   vars_files:
#     - vars.yml

#   pre_tasks:
#     - name: update repositories
#       apt:
#         update_cache: yes
#       changed_when: False

#   tasks:
#     - include: tasks/cron/setup.yml - DONE
#     - include: tasks/system/setup.yml - DONE
#     - include: tasks/git/setup.yml - DONE
#     - include: tasks/misc/apt-packages.yml - DONE
#     - include: tasks/dev/python/install.yml
#     - include: tasks/dev/misc/apt-packages.yml
#     - include: tasks/dev/node/install.yml
#     - include: tasks/dev/vagrant/install.yml
#     - include: tasks/apps/insync/install.yml - DONE
#     - include: tasks/apps/vscode/install.yml - DONE
#     - include: tasks/apps/vim/install.yml - DONE
#     - include: tasks/apps/tmux/install.yml - DONE
#     - include: tasks/apps/remmina/install.yml - DONE
#     - include: tasks/desktop/setup.yml - DONE
#     - include: tasks/desktop/plank.yml - DONE
#     - include: tasks/apps/virtualbox/install.yml
