- name: Install Visual Studio Code
  apt:
    deb: https://go.microsoft.com/fwlink/?LinkID=760868

- name: Install Visual Studio Code Extensions
  become_user: "{{user}}"
  script: files/install-extensions.sh

- name: Install Visual Studio Code User Settings
  become_user: "{{user}}"
  copy:
    src: files/settings.json
    dest: /home/{{user}}/.config/Code/User/