- name: Add an Virtualbox Apt signing key
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc

- name: Add Virtualbox PPA
  apt_repository:
    repo: deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian "{{ubuntu_codename}}" contrib

- name: Install Virtualbox
  apt:
    name: virtualbox-6.1
